use_default_settings: true

general:
debug: false
instance_name: "SearXNG"

search:
default_lang: "auto"
formats:
- html
- json

server:
secret_key: "7f3a91c8e24b6d10a5f927c41e8b63d2"
limiter: false
public_instance: false
image_proxy: true
